name: ExoticGarden
version: ${project.version}
author: TheBusyBiscuit
description: Fork italiana autonoma di ExoticGarden per Slimefun
website: https://github.com/Slimefun-Addon-Community/ExoticGarden

api-version: '1.13'
main: io.github.thebusybiscuit.exoticgarden.ExoticGarden

depend:
- Slimefun
